name: MovieBuzz
title: MovieBuzz| Movies, Series, Documentaries
description: A place to download your favourites.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
paginate: -4
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@xyz.com
disqus_username: disqus_username
